site_name: Inquirer Textual Documentation
repo_url: https://github.com/robvanderleek/inquirer-textual
theme:
  name: material
  palette:
  - scheme: slate
    primary: teal
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: default
    primary: teal
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: assets/logo-light.png
  favicon: assets/favicon.ico
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - content.code.copy
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - glightbox:
      draggable: false
      background: none
      shadow: false
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Inquirer Textual: 'index.md'
  - Getting Started: 'getting-started/index.md'
  - Prompts:
    - Checkbox: 'prompts/checkbox.md'
    - Confirm: 'prompts/confirm.md'
    - Editor: 'prompts/editor.md'
    - External: 'prompts/external.md'
    - Fuzzy: 'prompts/fuzzy.md'
    - Multi: 'prompts/multi.md'
    - Number: 'prompts/number.md'
    - Path: 'prompts/path.md'
    - Pattern: 'prompts/pattern.md'
    - Secret: 'prompts/secret.md'
    - Select: 'prompts/select.md'
    - Text: 'prompts/text.md'
    - Text Area: 'prompts/textarea.md'
    - Wait for key: 'prompts/wait_for_key.md'
  - CLI: 'cli/index.md'
  - Themes: 'themes/index.md'
  - Reference:
    - Checkbox: 'reference/checkbox.md'
    - Confirm: 'reference/confirm.md'
    - Editor: 'reference/editor.md'
    - Fuzzy: 'reference/fuzzy.md'
    - Multi: 'reference/multi.md'
    - Number: 'reference/number.md'
    - Path: 'reference/path.md'
    - Pattern: 'reference/pattern.md'
    - Secret: 'reference/secret.md'
    - Select: 'reference/select.md'
    - Text: 'reference/text.md'
    - Text Area: 'reference/textarea.md'
  - FAQ: 'faq.md'
